import { Metadata } from "next";
import Image from "next/image";
import { Cards } from "@/Components/cards";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {

  const dados: {imagem: string; titulo: string, cor: string, corInfo: string, corTexto: string}[] = [
    {
      imagem: "batata",
      titulo: "Batata Inglesa",
      cor: "bg-orange-800",
      corInfo: "bg-orange-600",
      corTexto: "text-orange-600"
    },
    {
      imagem: "batataAsterix",
      titulo: "Batata Asterix",
      cor: "bg-red-800",
      corInfo: "bg-red-600",
      corTexto: "text-red-600"
    },
    {
      imagem: "batataDoce",
      titulo: "Batata Doce",
      cor: "bg-blue-800",
      corInfo: "bg-blue-600",
      corTexto: "text-blue-600"
    }
  ]

  return (
    <>
    <div className="flex flex-row gap-32 justify-center mt-20 flex-wrap">
      {dados.map((item, index) => (
        <div key={index}>
          <Cards cor={item.cor} corInfo={item.corInfo} imagem={item.imagem} titulo={item.titulo} corTexto={item.corTexto}/>
        </div>
      ))}
    </div>
    </>
  );
}
